services:
  - type: web
    name: youtubeTime
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn youtubeTime.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: youtubeTime_db
          property: connectionString

databases:
  - name: youtubeTime_db
    databaseName: youtubeTime
    user: youtubeTime_user 